"""Alembic environment configuration for synchronous PostgreSQL migrations.

This module configures Alembic to work with PostgreSQL using synchronous
SQLAlchemy engine for migrations. The application uses async operations,
but migrations must be synchronous.
"""

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine, pool
from sqlalchemy.engine import Connection

# Import your Base and models
from app.models import Base

# This is the Alembic Config object
config = context.config

# Interpret the config file for Python logging
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Target metadata for autogenerate
target_metadata = Base.metadata


def get_database_url() -> str:
    """Get synchronous database URL for migrations.

    Alembic requires synchronous database operations, so we use
    psycopg2 instead of asyncpg for migrations.
    """
    # Try environment variable first (used in migrations)
    database_url = os.getenv("DATABASE_URL_SYNC")
    if database_url:
        return database_url

    # Build from components if not set
    host = os.getenv("DB_HOST", "localhost")
    port = os.getenv("DB_PORT", "5433")  # Using 5433 as per your setup
    user = os.getenv("DB_USER", "devops_user")
    password = os.getenv("DB_PASSWORD", "devops_pass")  # Updated password
    database = os.getenv("DB_NAME", "devops_assistant")

    return f"postgresql://{user}:{password}@{host}:{port}/{database}"


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well. By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.
    """
    url = get_database_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
        render_as_batch=False,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    """Run migrations with the given connection."""
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        compare_server_default=True,
        render_as_batch=False,
        # Include object name in autogenerated revision names
        process_revision_directives=process_revision_directives,
    )

    with context.begin_transaction():
        context.run_migrations()


def process_revision_directives(context, revision, directives):
    """Process revision directives to add meaningful names."""
    if getattr(config.cmd_opts, 'autogenerate', False):
        script = directives[0]
        if script.upgrade_ops.is_empty():
            directives[:] = []


def run_migrations_online() -> None:
    """Run migrations in 'online' mode with synchronous engine.

    In this scenario we create a synchronous Engine
    and associate a connection with the context.
    """
    # Create synchronous engine for migrations
    connectable = create_engine(
        get_database_url(),
        poolclass=pool.NullPool,  # No connection pooling for migrations
        echo=False,  # Set to True for debugging SQL
        future=True,
    )

    with connectable.connect() as connection:
        do_run_migrations(connection)


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
